apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert 
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  dnsNames:
  - '$exampleCert'